const {
  BLEND_ADD,
  BLEND_DARKEN,
  BLEND_DESTINATION_OVER,
  BLEND_DIFFERENCE,
  BLEND_EXCLUSION,
  BLEND_HARDLIGHT,
  BLEND_LIGHTEN,
  BLEND_MULTIPLY,
  BLEND_OVERLAY,
  BLEND_SCREEN,
  BLEND_SOURCE_OVER
} = require('jimp')

const modes = {
  ADD: BLEND_ADD,
  DARKEN: BLEND_DARKEN,
  DESTINATION_OVER: BLEND_DESTINATION_OVER,
  DIFFERENCE: BLEND_DIFFERENCE,
  EXCLUSION: BLEND_EXCLUSION,
  HARDLIGHT: BLEND_HARDLIGHT,
  LIGHTEN: BLEND_LIGHTEN,
  MULTIPLY: BLEND_MULTIPLY,
  OVERLAY: BLEND_OVERLAY,
  SCREEN: BLEND_SCREEN,
  SOURCE_OVER: BLEND_SOURCE_OVER
}

module.exports = modes